name: PushToS3
on:
  push:
    branches:
      - master
      - main

jobs:
  ClearBucket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Empty S3
        run: bash scripts/clearS3.sh ${{secrets.AWS_ACCESS_KEY_ID}} ${{secrets.AWS_SECRET_ACCESS_KEY}} quiz.tormod.dev
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to S3
        run: bash scripts/folderToS3.sh ${{secrets.AWS_ACCESS_KEY_ID}} ${{secrets.AWS_SECRET_ACCESS_KEY}} quiz.tormod.dev build
  invalidation:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Invalidate Cloudfront
        run: bash scripts/createInvalidation.sh ${{secrets.AWS_ACCESS_KEY_ID}} ${{secrets.AWS_SECRET_ACCESS_KEY}} ${{secrets.AWS_DISTRIBUTION_ID}}
